export const CREATE_LEARNING_PLAN = "CREATE_LEARNING_PLAN";
export const GET_LEARNING_PLANS_REQUEST = "GET_LEARNING_PLANS_REQUEST";
export const GET_LEARNING_PLANS_SUCCESS = "GET_LEARNING_PLANS_SUCCESS";
export const GET_LEARNING_PLANS_FAILURE = "GET_LEARNING_PLANS_FAILURE";
export const UPDATE_LEARNING_PLAN = "UPDATE_LEARNING_PLAN";
export const DELETE_LEARNING_PLAN = "DELETE_LEARNING_PLAN";
